language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get remove gcc-4.6 g++-4.6
  - sudo apt-get install gcc-4.7 g++-4.7
  - wget -O Qt5.1.1.zip https://dl.dropboxusercontent.com/u/20447449/Qt5.1.1.zip
  - mkdir ~/Qt5.1.1
  - unzip -qq Qt5.1.1.zip -d ~/Qt5.1.1
  - sudo chmod -R 777 ~/Qt5.1.1/
  - ln -s ~/Qt5.1.1/5.1.1/gcc_64/mkspecs/linux-g++ ~/Qt5.1.1/5.1.1/gcc_64/mkspecs/linux-gcc
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure && make -j3 check
  - sudo make install
  - sudo ldconfig
  - cd ..

script:
  - ~/Qt5.1.1/5.1.1/gcc_64/bin/qmake -v
  - ~/Qt5.1.1/5.1.1/gcc_64/bin/qmake -spec linux-$CC -Wall projectfiles/QtCreator/TOX-Qt-GUI.pro
  - make -j3

notifications:
  
  irc: 
    channels:
      - "chat.freenode.net#Tox-Qt-GUI"
    on_success: always
    on_failure: always
    